### PR TITLE
Add maildev to docker-compose setup. Fix #738.

### LINKED ISSUE #738: Add development server to docker compose?
It's really nice that this has docker-compose set up, as it makes for a really nice development experience.

However, to test a change I just ran `docker-compose up web`, and I get an error because the `MAIL_PASSWORD` environment variable is not found. Obviously in this case I'm not interested in setting up emails, so it would be nice to not have to worry about it.

Perhaps we can somehow add a `dev` option to docker-compose so I can run the server without worrying about this?

What do you think?

### PR DESCRIPTION
**Pull request by jezdez**

### CODE REVIEW

**Comment by jezdez** [comment]
@jstockwin Wanna try this out? This should give you an email server on port 1025 and a web UI on port [localhost:1080](http://localhost:1080/) to see the sent mails.

**Comment by jstockwin** [comment]
@jezdez so actually part of my issue was not reading the readme... I saw a docker-compose file and just did `docker-compose up`, but I can see I should have also done `make build` first.

That said, I am still having some issues. Firstly, I now get that `MAIL_PASSWORD` is not found, but that can (I think) be fixed by doing `MAIL_PASSWORD = config("MAIL_PASSWORD", None)` in `config.py`.

However now my `db` container exists saying `The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 13.0 (Debian 13.0-1.pgdg100+1)`. 

I will debug this further and try to get it working, then I can detail what I had to do and we can decide how to move forward.

**Comment by jezdez** [comment]
> @jezdez so actually part of my issue was not reading the readme... I saw a docker-compose file and just did `docker-compose up`, but I can see I should have also done `make build` first.

Make sure to copy the `.env-dist` to `.env` if you haven't already.

> That said, I am still having some issues. Firstly, I now get that `MAIL_PASSWORD` is not found, but that can (I think) be fixed by doing `MAIL_PASSWORD = config("MAIL_PASSWORD", None)` in `config.py`.
> 
> However now my `db` container exists saying `The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 13.0 (Debian 13.0-1.pgdg100+1)`.

Hmm, yeah, not sure about that, recreate the postgres container somehow? I always forget what to do for Docker containers, but I think it boils down from starting from scratch. In doubt just downgrade Postgres locally.

> I will debug this further and try to get it working, then I can detail what I had to do and we can decide how to move forward.

**Comment by jstockwin** [comment]
> Make sure to copy the .env-dist to .env if you haven't already.

Let's add that to the readme ;) I have not used node for a long time...

I have fixed postgres (by downgrading). This could have been because I already had an older image locally, not sure.

I've got everything working now. The other gotcha is that you have to access it via `https`. So going to `localhost:5000` does not work unless we add the `https`, and you also have to go past the browser complaining that the website is unsafe. Not sure what the fix for that is.. redirect? Don't use https in dev? Just add this to the readme so people know what to do?

Given #738 was actually just caused by these issues, your change in this PR isn't actually needed to get the server running... but perhaps it's still a nice change - that's up to you!

**Comment by jezdez** [comment]
The SSL bits will need more investigation, I think I had this working a while ago, need to double check what's going on.

**Comment by jstockwin** [comment]
Cool, I'll ping a quick PR to update the readme..

**Pull request merged**
